# Generated by Django 2.2.6 on 2019-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatedeposit',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='certificatedepositira',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='checking',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='moneymarket',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='savings',
            name='status',
            field=models.CharField(default='inactive', max_length=10),
        ),
    ]
