# Generated by Django 2.2.6 on 2019-10-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191020_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatedeposit',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='certificatedepositira',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='checking',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=9),
        ),
        migrations.AlterField(
            model_name='moneymarket',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=9),
        ),
        migrations.AlterField(
            model_name='savings',
            name='minimum',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=9),
        ),
    ]
