# Generated by Django 2.2.6 on 2019-10-21 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191020_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='zipcode',
            new_name='zip_code',
        ),
    ]
