# Generated by Django 2.2.6 on 2019-10-21 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191021_0322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_one', models.FileField(upload_to='uploads/')),
                ('document_two', models.FileField(upload_to='uploads/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
