# Generated by Django 2.2.6 on 2019-10-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191021_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_one',
            new_name='one',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='document_two',
            new_name='two',
        ),
    ]
