# Generated by Django 2.2.6 on 2019-10-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20191021_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
