# Generated by Django 2.2.6 on 2019-10-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_document_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='status',
            new_name='accepted',
        ),
    ]
