# Generated by Django 2.2.6 on 2019-10-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20191021_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatedeposit',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='certificatedepositira',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='checking',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='moneymarket',
            name='minimum',
        ),
        migrations.RemoveField(
            model_name='savings',
            name='minimum',
        ),
        migrations.AlterField(
            model_name='document',
            name='one',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='two',
            field=models.FileField(upload_to=''),
        ),
    ]
