# Generated by Django 2.2.6 on 2019-10-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20191021_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=25)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
            ],
        ),
    ]
