# Generated by Django 2.2.6 on 2019-10-22 02:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_deposit_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='deposit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
