# Generated by Django 2.2.6 on 2019-10-22 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_deposit_deposit_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savings',
            options={'verbose_name_plural': 'savings'},
        ),
    ]
