# Generated by Django 2.2.6 on 2019-10-22 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191021_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
